Upgrade to debian stretch
* Jessie is EOL was on 2018-06-17
* Jessie packages are outdated (ie, no jdk-11)
* Emdebian was dead since 2013
* osxcross is upgraded to the latest commit hash

The DarwinSDK needs to be updated, otherwise build fails:
```
In file included from code-sign-blobs/blob.cpp:29:
In file included from code-sign-blobs/blob.h:45:
In file included from code-sign-blobs/endian.h:34:
code-sign-blobs/memutils.h:96:42: error: unknown type name 'ptrdiff_t'; did you mean 'std::ptrdiff_t'?
inline const T *increment(const void *p, ptrdiff_t offset)
                                         ^~~~~~~~~
                                         std::ptrdiff_t
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/x86_64-linux-gnu/c++/6.3.0/bits/c++config.h:202:28: note: 'std::ptrdiff_t' declared here
  typedef __PTRDIFF_TYPE__      ptrdiff_t;
                                ^
```